### ISSUE TITLE
consider using slate-sugar for writing tests

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#1092]
Right now we use YAML for creating documents for tests, which is not bad honestly. But one thing I'd love to have is the entire test defined in a single file, so you wouldn't have to switch between `index.js`, `input.yaml` and `output.yaml` all the time.

With YAML this seems less nice, because defining YAML in JS means using big strings without highlighting. But with [`slate-sugar`](https://github.com/GitbookIO/slate-sugar) and JSX this might be nicer?

I could imagine a test file like:

```js
export const input = (
  <state>
    <document> 
      <paragraph>one</paragraph>
    </document>
    <selection 
        anchorKey="1" 
        anchorOffset={1} 
        focusKey="1" 
        focusKey={2}
    />
  </state>
)

export const output = (
  <state>
    <document> 
      <paragraph>oe</paragraph>
    </document>
    <selection 
        anchorKey="1" 
        anchorOffset={1} 
        focusKey="1" 
        focusKey={1}
    />
  </state>
)

export default function (change) {
  change.delete()
}
```

Or even defining a selection using `<anchor/>`, `<focus/>` and `<cursor/>`, like:

```js
export const input = (
  <state>
    <document> 
      <paragraph>
        o<anchor/>n<focus/>e
      </paragraph>
    </document>
  </state>
)

export const output = (
  <state>
    <document> 
      <paragraph>
        o<cursor/>e
      </paragraph>
    </document>
  </state>
)

export default function (change) {
  change.delete()
}
```

I think it could make tests a lot terser, and way easier to reason about.

cc @Soreine @SamyPesse

**Comment by ianstormtaylor** [comment]
For example, the `changes/fixtures/at-current-range/add-mark/across-blocks` test is currently:

```yaml
# input.yaml

nodes:
  - kind: block
    type: paragraph
    nodes:
      - kind: text
        text: word
  - kind: block
    type: paragraph
    nodes:
      - kind: text
        text: another
```
```yaml
# output.yaml

nodes:
  - kind: block
    type: paragraph
    nodes:
      - kind: text
        ranges:
          - text: wo
          - text: rd
            marks:
              - type: bold
  - kind: block
    type: paragraph
    nodes:
      - kind: text
        ranges:
          - text: an
            marks:
              - type: bold
          - text: other
```
```js
// index.js

import assert from 'assert'

export default function (state) {
  const { document, selection } = state
  const texts = document.getTexts()
  const first = texts.first()
  const second = texts.last()
  const range = selection.merge({
    anchorKey: first.key,
    anchorOffset: 2,
    focusKey: second.key,
    focusOffset: 2
  })

  const next = state
    .change()
    .select(range)
    .addMark('bold')
    .state

  assert.deepEqual(next.selection.toJS(), range.toJS())

  return next
}
```

---

But instead, it could be expressed much more simply as:

```js
// across-blocks.js

export const input = (
  <state>
    <document>
      <paragraph>
        wo<anchor/>rd
      </paragraph>
      <paragraph>
        an<focus/>other
      </paragraph>
    </document>
  </state>
)

export const input = (
  <state>
    <document>
      <paragraph>
        wo<anchor/><bold>rd</bold>
      </paragraph>
      <paragraph>
        <bold>an</bold><focus/>other
      </paragraph>
    </document>
  </state>
)

export default function (change) {
  change.addMark('bold')
}
```
