### ISSUE TITLE
re-combine split_node and merge_node operations

### ISSUE THREAD

**Issue by ianstormtaylor** [ianstormtaylor/slate#1127]
I think I just realized there's an issue with having separated these two operation types into being recursive. If you have a situation like this:

```js
o|ne t|wo
```

With two people, if they both press enter at the same time you'll end up with basically these operations being created:

```yaml
a:
  - split [0,0] 1
  - split [0] 1

b:
  - split [0,0] 5
  - split [0] 1
```

But it's not possible to know which of the second operations for `a` and `b` are "before/after" the other, since they don't contain the full information. All operations need to always contain "full" information so other operations can be evaluated against them.

I think this would be a requirement for #259.
