### ISSUE TITLE
getNextBlock cannot get isVoid block

### ISSUE THREAD

**Issue by zhujinxuan** [ianstormtaylor/slate#1525]
#### Do you want to request a *feature* or report a *bug*?
perhaps it is a bug

#### What's the current behavior?

Consider a document that 
```
document:
  - type: paragraph
     object: block
     key: '_cursor_'
     nodes: 
        text: "Cat is cute"
  - type: image
     object: block
     isVoid: true
```
Then `document.getNextBlock('_cursor_')` cannot get the image.  Because 
```
    const next = this.getNextText(last.key)
    if (!next) return null

    return this.getClosestBlock(next.key)
```

Is it designed to avoid the `void blocks`?
