### ISSUE TITLE
how to unwrap a block by key?

### ISSUE THREAD

**Issue by Soreine** [ianstormtaylor/slate#320]
Ideally, I would like to make a transform that unwrap a block by key.
My use case is to unwrap items in a list that have sublists inside them. If my understanding is correct, `unwrapBlock` and `unwrapBlockAtRange` both unwrap all blocks at range that match a type, or certain data. My problem is to unwrap just that parent list, not every children list too.
Would it be a solution to add a test on a `key` property [here](https://github.com/ianstormtaylor/slate/blob/8fc3631328481b3c56c48a56e1a9bad2eb24bd5a/lib/transforms/at-range.js#L599-L602) ? So that we can just unwrap a single block by key ?

---

On a side note, I'll explain my related issue. I am [struggling](https://github.com/GitbookIO/slate-edit-list/pull/16) to implement something that unwrap a block by two levels. Something that would extract a a list item from a list, and then unwrap that list item's children.

It would go from that (short notation):

``` yaml
- type: list
  nodes:
    - type: item
      nodes:
        - text: 1
    - type: item # Item with sublist to unwrap
      nodes:
        - text: 2
        - type: list
          nodes:
            - type: item
              nodes:
                - text: 2.1
            - type: item
              nodes:
                - text: 2.2
    - type: item
      nodes:
        - text: 3
```

To this:

``` yaml
- type: list
  nodes:
    - type: item
      nodes:
        - text: 1
# Unwrapped item's children
- text: 2
- type: list
  nodes:
    - type: item
      nodes:
        - text: 2.1
    - type: item
      nodes:
        - text: 2.2
# Notice that the root list was split
- type: list
  nodes:
    - type: item
      nodes:
        - text: 3
```

I think I need to make it in 2 steps :
1.  Extract the list item from its parent list. If the parent list becomes empty, delete it, else, just split it in two lists, and put the list item in between.
2.  Replace the extracted list item with its children.

I am not sure of what "unwrapping" means exactly. But I think we could say that 1. is unwrapping the list item from it's parent list, and 2. is unwrapping the list item's children from the list item.

I would greatly appreciate if anyone could confirm the meaning of "unwrapping", or provide advice on how to implement this transform neatly.

Thank you all
